### ISSUE TITLE
Autoupdates & Releases

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#3]
Building for OS X, Windows and Linux.

Implement update service for the application.

See:
https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by JoshuaKrueger** [comment]
No autoupdates -> because they are annoying!
Instead: check in couch for current_version, minimum_accepted_version. 
If client_current_version < minimum_accepted_version => force update

**Comment by JoshuaKrueger** [comment]
Create Version DB:
id, version_code, minimum_accepted_version, download_link, size

**Comment by bernd** [comment]
> No autoupdates -> because they are annoying!

@JoshuaKrueger 
I researched auto updates some time ago and also decided to not do it for now. Depending where you look,  those would require to buy a certificate to sign releases on macOS and Windows. This is a) expensive and b) complicates the release building process.

The Windows binary is currently an executable .exe which does not require any installation. So the users can just download the new version and start that one instead of the old one. I guess that's fine for now.

**Comment by niczem** [comment]
created #70
